name: Full CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout SCM
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 5️⃣ Build final JAR
      - name: Build JAR
        run: mvn clean package -DskipTests=true
        working-directory: Java-springboot-project/backend

      - name: Remove old JAR
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -f /home/ec2-user/app/target/datastore-0.0.7.jar
            sudo chown -R ec2-user:ec2-user /home/ec2-user/app

      # 6️⃣ Copy JAR to EC2
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: Java-springboot-project/backend/target/datastore-0.0.7.jar
          target: /home/ec2-user/app/target/
          overwrite: true

      # 7️⃣ Stop Old Application
      - name: Stop Old Application
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script_stop: false
          script: |
           PIDS=$(pgrep -f datastore-0.0.7.jar || true)

           if [ -n "$PIDS" ]; then
               echo "Stopping existing application(s): $PIDS"
               for PID in $PIDS; do
                 kill -9 $PID || true
               done 
           else
               echo "No existing application running"
           fi


      # 8️⃣ Run New Application (UPDATED ✔️)
      - name: Run Application on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /var/log/app
            sudo chown ec2-user:ec2-user /var/log/app

            cd /home/ec2-user/app/target/Java-springboot-project/backend/target

            nohup env \
              MYSQL_HOST=database-1.cxkq8gcu2wq9.ap-south-1.rds.amazonaws.com \
              MYSQL_PORT=3306 \
              MYSQL_USERNAME=admin \
              MYSQL_PASSWORD=bijaya123 \
              LOG_FILE_PATH=/var/log/app/datastore.log \
              java -jar datastore-0.0.7.jar \
              --server.port=8084 \
              --server.address=0.0.0.0 \
              > /var/log/app/nohup.out 2>&1 &

              sleep 10
              pgrep -fl datastore-0.0.7.jar || (echo "❌ App failed to start" && exit 1)

              echo "✅ Application started successfully"
